# Generated by Django 5.0.2 on 2025-10-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0002_administradores_delete_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='updated',
        ),
        migrations.AddField(
            model_name='administradores',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='clave_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
