# Generated by Django 5.0.2 on 2025-10-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0004_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
