# Generated by Django 5.0.2 on 2025-10-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0006_maestros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
    ]
