# Generated by Django 5.0.2 on 2025-11-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0007_remove_maestros_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_materia', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_escolar_api.maestros')),
            ],
        ),
    ]
